### ISSUE TITLE
icons task throwing phantomjs error

### ISSUE THREAD

**Issue by faresite** [maxboeck/jekyll-gulp#1]
Hey there,
Really like this setup, I think it's very neat!
Just a note, when I ran it the icons task was throwing a phantomjs related error and quitting.
```bash
[09:32:41] Starting 'icons'...
svg-to-png now spawning phantomjs...
(using path: /usr/local/lib/node_modules/phantomjs/lib/phantom/bin/phantomjs)

Something went wrong with phantomjs...
PHANTOM ERROR: TypeError: undefined is not an object (evaluating 'phantom.args[0]')
TRACE:
 -> phantomjs://code/phantomscript.js: 46
```
I just removed the icons task for now and it all seem to work perfectly fine. I really don't know my way around phantomjs so I can't help, but thought I'd mention it to you.

Thanks anyway!

**Comment by nathanbirrell** [comment]
+1 also getting this issue

**Comment by maxboeck** [comment]
fixed this in the recent version by replacing _grunticon_ with https://github.com/jkphl/gulp-svg-sprite for the icon task.

phantomjs had some issues with different node versions, and I find the SVG Sprite approach cleaner anyway. Please note that for cross-browser support (IE), this needs a polyfill like https://github.com/Keyamoon/svgxuse .
